FIX: Do NOT trigger jobs for those status!= GerritChangeStatus.NEW
jenkinsci/gerrit-trigger-plugin pull request #432
Opened 2021-04-25 09:31 UTC by chenhuahuan

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-04-25 09:34 UTC, chenhuahuan commented
See: https://issues.jenkins.io/browse/JENKINS-65462

2021-04-30 10:15 UTC, rsandell requested changes
Why?
The ticket doesn't seem to explain what the problem is and what the code fixes.
I would also like to see a unit test that recreates the issue.

2021-07-07 13:18 UTC, chenhuahuan commented
> Why?
> The ticket doesn't seem to explain what the problem is and what the code fixes.
> I would also like to see a unit test that recreates the issue.
---------------------------------------------------
>Just update the ticket.
> unit test brings too much extra work for me because the modified function doesn't have a unit test itself.

Please take a look at the ticket description , you will understand the issue and why this Pull Request fixs it.

2021-09-10 14:22 UTC, rsandell approved these changes

2021-09-10 17:48 UTC, rsandell commented
I am getting a lot of connection timeouts in the existing unit tests with this "fix" applied.

2021-09-12 17:00 UTC, chenhuahuan commented
Doesn't make sense. What the timeout is about? It seems not related to the modification, is it some kind of CI environment issue?

2022-11-11 07:43 UTC, ckreisl commented
The check if it's in state "NEW" might be at the wrong location. I think i got the idea why it should be in.
It's also related to the topic handling PR #468 in my name.

The first question is "When is a change interesting?"
For "Patchset Created" events the state should be always NEW.
In case the change gets abandoned during runtime an exception is raised that the plugin can't set a +/- 1 verified anymore after build completion.

But one might be interested in ref updated "MERGED" events. 
In my case it gets interesting with enabled "Topic Association". From my current point of view changes assigned to a topic which are already "MERGED" or "ABANDONED" shouldn't be taken into account. That's why we should only check for the "NEW" state.

I already started to do some adaption but it's not finalized yet.

2022-12-02 14:25 UTC, rsandell commented
was this superseded by #481 ?

2026-06-24 17:55 UTC, closed without merging